name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
          id-token: write
          pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: latest

      - name: Build
        run: npm i pnpm -g && pnpm install --frozen-lockfile && pnpm docs:build

      - name: Upload
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: kspider-docs/.vitepress/dist
          retention-days: 1

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          token: ${{ github.token }}
          preview: true
          timeout: 600000
          error_count: 10
          reporting_interval: 5000

